config/routes.rb
Rails.application.routes.draw do


  constraints subdomain: 'api' do
    scope module: 'api' do
      namespace :v1 do
        resources :users
        resources :orders
        resources :cloths
      end
    end
  end
  resources :cloths
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :orders
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cloth.rb
class Cloth < ApplicationRecord
	has_many :orders
	has_many :users ,through: :orders
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    belongs_to :cloth
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  has_many :orders
  has_many :cloths , through: :orders


  # Assign an API key on create
  before_create do |user|
    user.api_key = user.generate_api_key
  end

  # Generate a unique API key
  def generate_api_key
    loop do
      token = SecureRandom.base64.tr('+/=', 'Qrt')
      break token unless User.exists?(api_key: token)
    end
  end
end

app/controllers/api/v1/api_controller.rb
module Api::V1

	class ApiController < ApplicationController


		



	end

end

app/controllers/api/v1/cloths_controller.rb
module Api::v1
  class ClothsController < ApiController

    # GET /v1/cloths
    def index
      render json: Cloth.all
    end

  end
end

app/controllers/api/v1/orders_controller.rb
module Api::V1
  class OrdersController < ApiController

    # GET /v1/orders
    def index
      render json: Order.all
    end

  end
end

app/controllers/api/v1/users_controller.rb
module Api::V1
  class UsersController < ApiController

    # GET /v1/users
    def index

      render json: User.all
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# include ActionController::HttpAuthentication::Token::ControllerMethods
	
	# # Add a before_action to authenticate all requests.
	#  # Move this to subclassed controllers if you only
	#  # want to authenticate certain methods.

	#  before_action :authenticate

	#  protected

	#  # Authenticate the user with token based authentication
	#  def authenticate
	#    authenticate_token || render_unauthorized
	#  end

	#  def authenticate_token
	#    authenticate_with_http_token do |token, options|

	#      @current_user = User.find_by(api_key: token)
	#    end
	#  end

	#  def render_unauthorized(realm = "Application")
	#    self.headers["WWW-Authenticate"] = %(Token realm="#{realm}")
	#    render json: 'Bad credentials', status: :unauthorized
	#  end
end

app/controllers/cloths_controller.rb
class ClothsController < InheritedResources::Base

  private

    def cloth_params
      params.require(:cloth).permit(:name)
    end

end

app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base

  private

    def order_params
      params.require(:order).permit(:id, :latitude, :longitude, :price, :order_type, :user_id)
    end

end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base

  private

    def user_params
      params.require(:user).permit(:name, :phone_number, :email, :address)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cloths_helper.rb
module ClothsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cloths/_form.html.erb
<%= form_with(model: cloth, local: true) do |form| %>
  <% if cloth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cloth.errors.count, "error") %> prohibited this cloth from being saved:</h2>

      <ul>
      <% cloth.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cloths/edit.html.erb
<h1>Editing Cloth</h1>

<%= render 'form', cloth: @cloth %>

<%= link_to 'Show', @cloth %> |
<%= link_to 'Back', cloths_path %>

app/views/cloths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cloths</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cloths.each do |cloth| %>
      <tr>
        <td><%= cloth.name %></td>
        <td><%= link_to 'Show', cloth %></td>
        <td><%= link_to 'Edit', edit_cloth_path(cloth) %></td>
        <td><%= link_to 'Destroy', cloth, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cloth', new_cloth_path %>

app/views/cloths/new.html.erb
<h1>New Cloth</h1>

<%= render 'form', cloth: @cloth %>

<%= link_to 'Back', cloths_path %>

app/views/cloths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cloth.name %>
</p>

<%= link_to 'Edit', edit_cloth_path(@cloth) %> |
<%= link_to 'Back', cloths_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SticherRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.number_field :id %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :order_type %>
    <%= form.text_field :order_type %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Price</th>
      <th>Order type</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.latitude %></td>
        <td><%= order.longitude %></td>
        <td><%= order.price %></td>
        <td><%= order.order_type %></td>
        <td><%= order.user_id %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @order.id %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @order.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @order.longitude %>
</p>

<p>
  <strong>Price:</strong>
  <%= @order.price %>
</p>

<p>
  <strong>Order type:</strong>
  <%= @order.order_type %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user_id %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone number</th>
      <th>Email</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.phone_number %></td>
        <td><%= user.email %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @user.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>